version: "3"

services:

  consul:
    image: consul:latest
    container_name: consul
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
      - "172.17.0.1:53:53/udp"

  neo4j-service:
    image: neo4j:3.4.7
    container_name: neo4j-service
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      #For testing purposes only
      NEO4J_AUTH: none
